# Generated by Django 5.1.2 on 2025-05-07 21:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_doctor', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3)])),
                ('anos_experiencia', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('email_doctor', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('telefono_doctor', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion_doctor', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Especialidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_especialidad', models.CharField(max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(3)])),
            ],
        ),
        migrations.CreateModel(
            name='Pacientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_paciente', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3)])),
                ('apellido1_paciente', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3)])),
                ('apellido2_paciente', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3)])),
                ('edad_paciente', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('email_paciente', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('direccion_paciente', models.TextField(blank=True, null=True)),
                ('telefono_paciente', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doctores_Especialidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.doctores')),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.especialidades')),
            ],
        ),
        migrations.AddField(
            model_name='doctores',
            name='especialidad',
            field=models.ManyToManyField(through='api.Doctores_Especialidades', to='api.especialidades'),
        ),
        migrations.CreateModel(
            name='Citas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('motivo', models.TextField(blank=True, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.doctores')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pacientes')),
            ],
        ),
    ]
